//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.FX.Sql.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ES.FX.Sql.Server.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE [@Database].
        /// </summary>
        internal static string Database_Create {
            get {
                return ResourceManager.GetString("Database_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE [@Database]  (SERVICE_OBJECTIVE= ELASTIC_POOL (name = [@ElasticPool])).
        /// </summary>
        internal static string Database_Create_Azure_Pool {
            get {
                return ResourceManager.GetString("Database_Create_Azure_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE [@Database]  (SERVICE_OBJECTIVE=@ServiceObjective, EDITION=@Edition).
        /// </summary>
        internal static string Database_Create_Azure_Single {
            get {
                return ResourceManager.GetString("Database_Create_Azure_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP DATABASE [@Database];.
        /// </summary>
        internal static string Database_Drop {
            get {
                return ResourceManager.GetString("Database_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER DATABASE [@Database] set single_user with rollback immediate;
        ///DROP DATABASE [@Database];.
        /// </summary>
        internal static string Database_Drop_CloseConnections {
            get {
                return ResourceManager.GetString("Database_Drop_CloseConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT name FROM sys.databases.
        /// </summary>
        internal static string Database_Get_All {
            get {
                return ResourceManager.GetString("Database_Get_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DB_ID(@Database).
        /// </summary>
        internal static string Database_ID {
            get {
                return ResourceManager.GetString("Database_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT name FROM sys.schemas.
        /// </summary>
        internal static string Database_Schemas_Get_All {
            get {
                return ResourceManager.GetString("Database_Schemas_Get_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SERVERPROPERTY (@Property).
        /// </summary>
        internal static string Server_Property_Get {
            get {
                return ResourceManager.GetString("Server_Property_Get", resourceCulture);
            }
        }
    }
}
